version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:00"
    open-pull-requests-limit: 1
    groups:
      all-go-deps:
        applies-to: version-updates
        patterns: ["*"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:00"
    open-pull-requests-limit: 1
    groups:
      all-actions:
        applies-to: version-updates
        patterns: ["*"]
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:00"
    open-pull-requests-limit: 1
    groups:
      all-docker:
        applies-to: version-updates
        patterns: ["*"]
