linters:
  disable:
    - gosimple
    - errcheck
    - ineffassign
    - staticcheck

  enable:
    - goimports # Check import statements are formatted according to the 'goimport' command. Reformat imports in autofix mode.
    - importas # Enforces consistent import aliases.
    - misspell # Finds commonly misspelled English words.
